### ISSUE TITLE
build arm binaries

### ISSUE THREAD

**Issue by c-nv-s** [freedomlayer/offset#289]
if possible please could you also build and support arm6/7 and arm64 binaries in your releases.

**Comment by realcr** [comment]
Hey @c-nv-s, thanks for opening this issue!
Just to make sure I understand what you mean, you want to add arm6/7 and arm64 targets for Linux?

Currently the following Android targets are built automatically:
- aarch64
- armv7
- i686
(See: https://github.com/freedomlayer/offset/releases)

Do you have a desktop environment that runs on arm6/7 and arm64?

**Comment by c-nv-s** [comment]
apologies, I can see since 18 days ago this has already begun. Thanks! keep up the good work

**Comment by c-nv-s** [comment]
Perhaps you could also make  the app available on F-droid 
https://f-droid.org/

**Comment by realcr** [comment]
Superseded by https://github.com/freedomlayer/offset_mobile/issues/14
Thanks!
